title: Anylinux AppImages
description: AppImages that run on any Linux distribution
baseurl: "/Anylinux-AppImages"
url: "https://pkgforge-dev.github.io"
logo: "/assets/logo.svg"
social_image: "/assets/opengraph.png"
author: pkgforge-dev

markdown: kramdown
highlighter: rouge

exclude:
  - useful-tools/
  - .github/
